#!/usr/bin/env python3
"""
Generate typeEffectiveness.js from Python TYPE_EFFECTIVENESS data.

This script ensures type effectiveness data is consistent between
Python (pokeapi_fetch.py) and JavaScript (assets/js/utils/typeEffectiveness.js).
"""

import json
import logging
from datetime import datetime

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Type effectiveness chart - damage multipliers
# This is the single source of truth for type matchups
TYPE_EFFECTIVENESS = {
    "normal": {"rock": 0.5, "ghost": 0, "steel": 0.5},
    "fire": {"fire": 0.5, "water": 0.5, "grass": 2, "ice": 2, "bug": 2, "rock": 0.5, "dragon": 0.5, "steel": 2},
    "water": {"fire": 2, "water": 0.5, "grass": 0.5, "ground": 2, "rock": 2, "dragon": 0.5},
    "electric": {"water": 2, "electric": 0.5, "grass": 0.5, "ground": 0, "flying": 2, "dragon": 0.5},
    "grass": {"fire": 0.5, "water": 2, "grass": 0.5, "poison": 0.5, "ground": 2, "flying": 0.5, "bug": 0.5, "rock": 2, "dragon": 0.5, "steel": 0.5},
    "ice": {"fire": 0.5, "water": 0.5, "grass": 2, "ice": 0.5, "ground": 2, "flying": 2, "dragon": 2, "steel": 0.5},
    "fighting": {"normal": 2, "ice": 2, "poison": 0.5, "flying": 0.5, "psychic": 0.5, "bug": 0.5, "rock": 2, "ghost": 0, "dark": 2, "steel": 2, "fairy": 0.5},
    "poison": {"grass": 2, "poison": 0.5, "ground": 0.5, "rock": 0.5, "ghost": 0.5, "steel": 0, "fairy": 2},
    "ground": {"fire": 2, "electric": 2, "grass": 0.5, "poison": 2, "flying": 0, "bug": 0.5, "rock": 2, "steel": 2},
    "flying": {"electric": 0.5, "grass": 2, "fighting": 2, "bug": 2, "rock": 0.5, "steel": 0.5},
    "psychic": {"fighting": 2, "poison": 2, "psychic": 0.5, "dark": 0, "steel": 0.5},
    "bug": {"fire": 0.5, "grass": 2, "fighting": 0.5, "poison": 0.5, "flying": 0.5, "psychic": 2, "ghost": 0.5, "dark": 2, "steel": 0.5, "fairy": 0.5},
    "rock": {"fire": 2, "ice": 2, "fighting": 0.5, "ground": 0.5, "flying": 2, "bug": 2, "steel": 0.5},
    "ghost": {"normal": 0, "psychic": 2, "ghost": 2, "dark": 0.5},
    "dragon": {"dragon": 2, "steel": 0.5, "fairy": 0},
    "dark": {"fighting": 0.5, "psychic": 2, "ghost": 2, "dark": 0.5, "fairy": 0.5},
    "steel": {"fire": 0.5, "water": 0.5, "electric": 0.5, "ice": 2, "rock": 2, "steel": 0.5, "fairy": 2},
    "fairy": {"fire": 0.5, "fighting": 2, "poison": 0.5, "dragon": 2, "dark": 2, "steel": 0.5}
}


def generate_javascript_file(output_path: str = "assets/js/utils/typeEffectiveness.js") -> None:
    """Generate JavaScript file from TYPE_EFFECTIVENESS data.
    
    Args:
        output_path: Path to output JavaScript file
    """
    logger.info(f"Generating {output_path} from Python TYPE_EFFECTIVENESS data...")
    
    # Convert Python dict to JavaScript object literal
    js_content = f"""/**
 * Type Effectiveness Data
 * 
 * This file is AUTO-GENERATED by generate_type_effectiveness.py
 * DO NOT EDIT MANUALLY - changes will be overwritten
 * 
 * To update type effectiveness data:
 * 1. Edit TYPE_EFFECTIVENESS in pokeapi_fetch.py
 * 2. Run: python generate_type_effectiveness.py
 * 
 * Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
 */

/**
 * Type effectiveness multipliers for Pokemon type matchups
 * 
 * Structure: {{attacking_type: {{defending_type: multiplier}}}}
 * 
 * Multipliers:
 * - 2.0: Super effective
 * - 1.0: Normal damage (not listed)
 * - 0.5: Not very effective
 * - 0: No effect (immune)
 * 
 * @type {{Object.<string, Object.<string, number>>}}
 */
export const TYPE_EFFECTIVENESS = {json.dumps(TYPE_EFFECTIVENESS, indent=2)};

/**
 * Calculate damage multiplier for an attacking type against defending types
 * 
 * @param {{string}} attackingType - The type of the attacking move
 * @param {{Array<string>}} defendingTypes - Array of defending Pokemon's types
 * @returns {{number}} Combined damage multiplier
 */
export function calculateTypeEffectiveness(attackingType, defendingTypes) {{
    let multiplier = 1;
    
    const effectiveness = TYPE_EFFECTIVENESS[attackingType.toLowerCase()] || {{}};
    
    for (const defendingType of defendingTypes) {{
        const typeMultiplier = effectiveness[defendingType.toLowerCase()];
        if (typeMultiplier !== undefined) {{
            multiplier *= typeMultiplier;
        }}
    }}
    
    return multiplier;
}}

/**
 * Get effectiveness category for a multiplier
 * 
 * @param {{number}} multiplier - Damage multiplier
 * @returns {{string}} Category: 'immune', 'not-very-effective', 'normal', or 'super-effective'
 */
export function getEffectivenessCategory(multiplier) {{
    if (multiplier === 0) return 'immune';
    if (multiplier < 1) return 'not-very-effective';
    if (multiplier > 1) return 'super-effective';
    return 'normal';
}}

/**
 * Get all types that a given type is super effective against
 * 
 * @param {{string}} attackingType - The attacking type
 * @returns {{Array<string>}} Array of type names
 */
export function getSuperEffectiveAgainst(attackingType) {{
    const effectiveness = TYPE_EFFECTIVENESS[attackingType.toLowerCase()] || {{}};
    return Object.keys(effectiveness).filter(type => effectiveness[type] > 1);
}}

/**
 * Get all types that a given type is not very effective against
 * 
 * @param {{string}} attackingType - The attacking type
 * @returns {{Array<string>}} Array of type names
 */
export function getNotVeryEffectiveAgainst(attackingType) {{
    const effectiveness = TYPE_EFFECTIVENESS[attackingType.toLowerCase()] || {{}};
    return Object.keys(effectiveness).filter(type => effectiveness[type] < 1 && effectiveness[type] > 0);
}}

/**
 * Get all types that a given type has no effect against
 * 
 * @param {{string}} attackingType - The attacking type
 * @returns {{Array<string>}} Array of type names
 */
export function getNoEffectAgainst(attackingType) {{
    const effectiveness = TYPE_EFFECTIVENESS[attackingType.toLowerCase()] || {{}};
    return Object.keys(effectiveness).filter(type => effectiveness[type] === 0);
}}
"""
    
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    logger.info(f"Successfully generated {output_path}")
    logger.info(f"Type count: {len(TYPE_EFFECTIVENESS)}")
    
    # Count total matchups
    total_matchups = sum(len(matchups) for matchups in TYPE_EFFECTIVENESS.values())
    logger.info(f"Total matchup definitions: {total_matchups}")


if __name__ == "__main__":
    generate_javascript_file()
    logger.info("Type effectiveness generation complete!")
