name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  build:
    name: 🛠️ Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Archive production artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-dist
          path: build/    # adjust if your build dir is different

  test:
    name: ✅ Test
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: app-dist

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  deploy:
    name: 🚀 Deploy to AWS
    runs-on: ubuntu-latest
    needs: [build, test]
    if: github.ref == 'refs/heads/main' && success()
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ''      # optional, if using roles
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync build to S3
        run: |
          aws s3 sync build/ s3://YOUR_BUCKET_NAME/ --delete

      - name: Create CloudFront invalidation
        if: secrets.CLOUDFRONT_DISTRIBUTION_ID
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
